todo/__init__.py
import os
from os.path import join, dirname
from flask import Flask
from .extensions import mongo
from dotenv import load_dotenv
from todo.main.routes import main

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

MONGO_URI = os.environ.get('MONGO_URI')


def create_app():
    todoapp = Flask(__name__)
    todoapp.config['MONGO_URI'] = MONGO_URI
    todoapp.register_blueprint(main)
    mongo.init_app(todoapp)
    return todoapp

todo/main/routes.py
from flask import Blueprint, render_template, request, url_for, redirect
from todo.extensions import mongo
from bson import ObjectId

main = Blueprint('main', __name__)


@main.route('/')
def index():
    todo_db = mongo.db.todo
    todos = todo_db.find()
    return render_template('index.html', todos=todos)


@main.route('/api/add', methods=['POST'])
def add():
    todo_db = mongo.db.todo
    todo_item = request.form.get('add-todo')
    todo_db.insert_one({'text': todo_item, 'complete': False})
    return redirect(url_for('main.index'))


@main.route('/api/update/<id>', methods=['GET'])
def done(id):
    todo_db = mongo.db.todo
    todo_db.update_one({"_id": ObjectId(id)}, {"$set": {'complete': True}})

    return redirect(url_for('main.index'))


@main.route('/edit/<id>', methods=['GET', 'POST'])
def edit(id):
    todo_db = mongo.db.todo
    todo_item = todo_db.find_one({"_id": ObjectId(id)})
    if (request.method == 'GET'):
        return render_template('edit_task.html', todo=todo_item)
    elif (request.method == 'POST'):
        new_text = request.form.get('edited-todo')
        todo_db.update_one({"_id": ObjectId(id)}, {"$set": {'text': new_text}})
        return redirect(url_for('main.index'))


@ main.route("/api/delete/<id>", methods=['GET'])
def delete(id):
    todo_db = mongo.db.todo
    todo_db.delete_one({"_id": ObjectId(id)})
    return redirect(url_for('main.index'))

todo/templates/edit_task.html
{% include './header.html' %}

<h1 class="heading">Edit To Do</h1>

<div class="main-form">
  <form
    action="{{ url_for('main.edit', id=todo._id) }}"
    method="POST"
    role="form"
    class="form-inline"
  >
    <div class="input-group mb-4">
      <input
        name="edited-todo"
        type="text"
        class="form-control"
        value="{{ todo.text }}"
        aria-label="New Task"
        aria-describedby="button-addon1"
      />
      <div class="input-group-append">
        <button
          class="btn btn-outline-secondary"
          type="submit"
          id="button-addon1"
        >
          Edit
        </button>
      </div>
    </div>
  </form>
</div>

todo/templates/form.html
<div class="main-form">
  <form
    action="{{ url_for('main.add') }}"
    method="POST"
    role="form"
    class="form-inline"
  >
    <div class="input-group mb-4">
      <input
        name="add-todo"
        type="text"
        class="form-control"
        placeholder="New todo"
        aria-label="New Task"
        aria-describedby="button-addon1"
      />
      <div class="input-group-append">
        <button
          class="btn btn-outline-secondary"
          type="submit"
          id="button-addon1"
        >
          Add
        </button>
      </div>
    </div>
  </form>
</div>

todo/templates/header.html
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8" />
  <meta
    name="viewport"
    content="width=device-width, initial-scale=1, shrink-to-fit=no"
  />

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
  />
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
    crossorigin="anonymous"
  ></script>
  <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}" />

  <title>To Do</title>
</head>

todo/templates/index.html
<!DOCTYPE html>
<html lang="en">
  {% include './header.html' %}

  <body>
    <h1 class="heading">To Do</h1>
    {% include './form.html' %} {% include './table.html' %}
  </body>
</html>

todo/templates/table.html
<div class="todo-table">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">All Tasks</th>
      </tr>
    </thead>
    <tbody>
      {% for todo in todos %}
      <tr>
        {% if todo.complete == true %}
        <td>
          <span style="color: black; text-decoration: line-through">
            <span style="color: #b1b1b1"> {{ todo.text }} </span>
          </span>
        </td>
        {% else %}
        <td>{{ todo.text }}</td>
        {% endif %}
        <td>
          <a
            href="{{ url_for('main.edit', id=todo._id) }}"
            class="btn btn-light btn-sm"
          >
            <i class="bi bi-pencil-square"></i>
          </a>
          <a
            class="btn btn-light btn-sm"
            href="{{ url_for('main.done', id=todo._id) }}"
          >
            <i class="bi bi-check2-square"></i>
          </a>
          <a
            class="btn btn-light btn-sm"
            href="{{ url_for('main.delete', id=todo._id) }}"
          >
            <i class="bi bi-trash3"></i>
          </a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>